FROM node:alpine3.10
COPY . /app
WORKDIR /app
CMD node app.js



















# labuser@ip-172-31-1-17:~/MyDockerApp$ sudo su
# root@ip-172-31-1-17:/home/labuser/MyDockerApp# docker build -t hello-app:1.0 .
# [+] Building 1.1s (8/8) FINISHED                                                                                                                         docker:default
#  => [internal] load build definition from Dockerfile                                                                                                               0.0s
#  => => transferring dockerfile: 98B                                                                                                                                0.0s
#  => [internal] load metadata for docker.io/library/node:alpine3.10                                                                                                 0.4s
#  => [internal] load .dockerignore                                                                                                                                  0.0s
#  => => transferring context: 2B                                                                                                                                    0.0s
#  => [internal] load build context                                                                                                                                  0.5s
#  => => transferring context: 56B                                                                                                                                   0.0s
#  => [1/3] FROM docker.io/library/node:alpine3.10@sha256:c392d12c89f7345dfa7192162bc0edc84f29278d2002b6df0db1314284748032                                           0.0s
#  => CACHED [2/3] COPY . /app                                                                                                                                       0.0s
#  => CACHED [3/3] WORKDIR /app                                                                                                                                      0.0s
#  => exporting to image                                                                                                                                             0.0s
#  => => exporting layers                                                                                                                                            0.0s
#  => => writing image sha256:c2f99891776decd8fb6e0eca6639756e0f820467f09b3db08bbc09eaaabcf266                                                                       0.0s
#  => => naming to docker.io/library/hello-app:1.0                                                                                                                   0.0s
# root@ip-172-31-1-17:/home/labuser/MyDockerApp# docker images
# REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
# hello-app    1.0       c2f99891776d   31 seconds ago   111MB
# ubuntu       latest    3db8720ecbf5   2 weeks ago      77.9MB
# root@ip-172-31-1-17:/home/labuser/MyDockerApp# docker run hello-app:1.0
# OLA CHENNAI 1
# root@ip-172-31-1-17:/home/labuser/MyDockerApp# 




